name: Publish using connectors mapping

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      environment:
        required: true
        type: string
      repo-location:
        required: true
        type: string
      connectors-endpoint:
        required: true
        type: string
      command:
        required: true
        type: string
      email:                # pending to delete
        required: true
        type: string
      username:             # pending to delete
        required: true
        type: string
      metadata:
        required: true
        type: string
    secrets:
      cloud-access-token:
        required: false
      github-token:
        required: false
      connectors-token:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - uses: actions/checkout@v3

      # run metadata
      - run: echo "This is the metadata variable"

      - run: |
          echo ${{ inputs.type }}
          echo ${{ inputs.environment }}
          echo ${{ inputs.repo-location }}
          echo ${{ inputs.connectors-endpoint }}
          echo ${{ inputs.command }}

      - run: |
          repos=$(curl -s -X GET -H "Accept: application/json" "http://34.135.100.19:8080/connectors/mapping/retrieve/app" )
          echo $repos
          curl -s -X POST -H "Accept: application/json" \
          "https://api.github.com/repos/yabinboxes/pulumi-cloud-run/dispatches" \
          -d '{ "event_type": "build", "client_payload": { \
            "email": "ema", \
            "command": "up"", \
            "repo-location": "repo", \
            "environment": "dev", \
            "type": "app", \
            "cloud-access-token": "acc1", \
            "connectors-token": "acc2", |
            "metadata": "[ myOrg, myPrj ]", \
            "token": "acc3"
            }}'

          
#-X POST \
#          -H "Accept: application/json" \
#          ${connectorsEndpoint}/connectors/mapping/retrieve/${type} \
#          -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'
                
