name: Publish using connectors mapping

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      environment:
        required: true
        type: string
      repo-location:
        required: true
        type: string
      connectors-endpoint:
        required: true
        type: string
      command:
        required: true
        type: string
      email:                # pending to delete
        required: true
        type: string
      username:             # pending to delete
        required: true
        type: string
      metadata:
        required: true
        type: string
    secrets:
      cloud-access-token:
        required: false
      github-token:
        required: false
      connectors-token:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - uses: actions/checkout@v3

      - name: print public variables
        run: |
          echo ${{ inputs.type }}
          echo ${{ inputs.environment }}
          echo ${{ inputs.repo-location }}
          echo ${{ inputs.connectors-endpoint }}
          echo ${{ inputs.command }}
          echo ${{ inputs.metadata }}

      - name: get mapping
        id: mapping
        run: |
          echo "repos=$(curl -s -X GET -H 'Accept: application/json' '${{ inputs.connectors-endpoint }}/connectors/mapping/retrieve/${{ inputs.type }}')" >> "$GITHUB_OUTPUT"
      
      - name: call connectors
        run: |
          echo "connectors response ${{ steps.mapping.outputs.repos }}"
          curl -s -X POST -H "Accept: application/json" \
          "https://api.github.com/repos/${{ inputs.username }}/${{ steps.mapping.outputs.repos }}/dispatches" \
          -d '{ "event_type": "build", "client_payload": { \
          "email": ${{ inputs.email }}, \
          "command": ${{ inputs.command }}, \
          "repo-location": "https://github.com/${{ inputs.username }}/${{ inputs.repo-location }}", \
          "environment": ${{ inputs.environment }}, \
          "type": ${{ inputs.type }}, \
          "cloud-access-token": ${{ secrets.cloud-access-token }}, \
          "connectors-token": ${{ secrets.connectors-token }}, \
          "github-token": ${{ secrets.github-token}}, \
          "metadata": ${{ inputs.metadata }}, \
          }}'
      
 
                
