name: Publish using connectors mapping

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      environment:
        required: true
        type: string
      repo-location:
        required: true
        type: string
      connectors-endpoint:
        required: true
        type: string
      command:
        required: true
        type: string
      email:                # pending to delete
        required: true
        type: string
      username:             # pending to delete
        required: true
        type: string
      metadata:
        required: true
        type: string
    secrets:
      cloud-access-token:
        required: false
      github-token:
        required: false
      connectors-token:
        required: false

env:
  CONNECTORS_TYPE: ${{ inputs.type }}
  CONNECTORS_ENVIRONMENT: ${{ inputs.environment }}
  CONNECTORS_REPO_LOCATION: ${{ inputs.repo-location }}
  CONNECTORS_ENDPOINT: ${{ inputs.connectors-endpoint }}
  CONNECTORS_COMMAND: ${{ inputs.command }}
  CONNECTORS_METADATA: ${{ inputs.metadata }}
  SECRETS_CLOUD_TOKEN: ${{ secrets.cloud-access-token }}
  SECRETS_GITHUB_TOKEN: ${{ secrets.github-token}}
  SECRETS_CONNECTORS_TOKEN: ${{ secrets.connectors-token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - uses: actions/checkout@v3

      - run: ls

      # run metadata
      - run: echo "This is the metadata variable"

      - run: |
          echo ${{ inputs.type }}
          echo ${{ inputs.environment }}
          echo ${{ inputs.repo-location }}
          echo ${{ inputs.connectors-endpoint }}
          echo ${{ inputs.command }}
          echo ${{ inputs.metadata }}
      
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16
      
#      - run: npm ci

#      - run: node index.js


      - name: Hello world
        run: |
          echo "repos=$(curl -s -X GET -H 'Accept: application/json' '${{ inputs.connectors-endpoint }}/connectors/mapping/retrieve/${{ inputs.type }}')" >> $GITHUB_ENV
          echo ${{ env.repos }}
          curl -s -X POST -H "Accept: application/json" \
          "https://api.github.com/repos/${{ inputs.username }}/${{ env.repos }}/dispatches" \
          -d '{ "event_type": "build", "client_payload": { \
            "email": ${{ inputs.email }}, \
            "command": ${{ inputs.command }}, \
            "repo-location": "https://github.com/${{ inputs.username }}/${{ inputs.repo-location }}", \
            "environment": ${{ inputs.environment }}, \
            "type": ${{ inputs.type }}, \
            "cloud-access-token": ${{ secrets.cloud-access-token }}, \
            "connectors-token": ${{ secrets.connectors-token }}, \
            "github-token": ${{ secrets.github-token}}, \
            "metadata": ${{ inputs.metadata }}, \
            }}'
        env:
          repos: ''
                
