name: Publish using connectors mapping

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      environment:
        required: true
        type: string
      repo-location:
        required: true
        type: string
      connectors-endpoint:
        required: true
        type: string
      command:
        required: true
        type: string
      email:                # pending to delete
        required: true
        type: string
      username:             # pending to delete
        required: true
        type: string
      metadata:
        required: true
        type: string
    secrets:
      cloud-access-token:
        required: false
      github-token:
        required: false
      connectors-token:
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      
      - name: print public variables
        run: |
          echo ${{ inputs.type }}
          echo ${{ inputs.environment }}
          echo ${{ inputs.repo-location }}
          echo ${{ inputs.connectors-endpoint }}
          echo ${{ inputs.command }}
          echo ${{ inputs.metadata }}

      - name: get mapping
        id: mapping
        run: |
          echo "repos=$(curl -s -X GET -H 'Accept: application/json' '${{ inputs.connectors-endpoint }}/connectors/mapping/retrieve/${{ inputs.type }}')" >> "$GITHUB_OUTPUT"
      
      - name: dispatch connectors
        run: |
          echo "connectors response ${{ steps.mapping.outputs.repos }}"
          curl --location --request POST 'http://104.154.94.62:8080/connectors/orchestrator/dispatch/connectors-pulumi-gcp-bucket' \
          --header 'Content-Type: application/json' \
          --data-raw '{ "email": "yabin.monroy.1@gmail.com", "username": "yabinboxes", "command": "up", "repo-location": "test-cloud-flow", "environment": "dev", "type": "bucket"}'

#          curl -s \
#          -X POST \
#          -H 'Accept: application/json' \
#          '${{ inputs.connectors-endpoint }}/connectors/orchestrator/dispatch/${{ steps.mapping.outputs.repos }}' \
#          -d '{ "email": "${{ inputs.email }}", "username": "${{ inputs.username }}", "command": "${{ inputs.command }}", "repo-location": "${{ inputs.repo-location }}", "environment": "${{ inputs.environment }}", "type": "${{ inputs.type }}"}'


# Notes: 1. response mapping is not empty

#      - name: checkout public pulumi code with connectors
#        uses: actions/checkout@v3
#        with:
#          repository: "https://github.com/yabinboxes/${{ steps.mapping.outputs.repos }}"
#          path: connectors

      # setup node js 16
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16
          
#      - run: npm ci

      # setup auth google
#      - id: "auth"
#        name: "Authenticate to Google Cloud"
#        uses: "google-github-actions/auth@v0"
#        with:
#          credentials_json: "${{ secrets.cloud-access-token }}"


      #bucket
#      - name: call connectors
#        run: |
#          echo "connectors response ${{ steps.mapping.outputs.repos }}"
#          curl -L \
#          -X POST \
#          -H "Accept: application/vnd.github+json" \
#          -H "Authorization: Bearer ${{ secrets.github-token}}" \
#          -H "X-GitHub-Api-Version: 2022-11-28" \
#          "https://api.github.com/repos/${{ inputs.username }}/${{ steps.mapping.outputs.repos }}/dispatches" \
#          -d '{ "event_type": "build", "client_payload": { \
#          "email": "${{ inputs.email }}", \
#          "command": "${{ inputs.command }}", \
#          "repo-location": "https://github.com/${{ inputs.username }}/${{ inputs.repo-location }}", \
#          "environment": "${{ inputs.environment }}", \
#          "type": "${{ inputs.type }}", \
#          "cloud-access-token": "${{ secrets.cloud-access-token }}", \
#          "connectors-token": "${{ secrets.connectors-token }}", \
#          "github-token": "${{ secrets.github-token}}", \
#          "metadata": "${{ inputs.metadata }}" \
#          }}'
      
 
                
